# version: '3.9'

services:
    # Database Service
    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-mysql
        ports:
            - ${MYSQL_SERVICE_PORT?Not mysql port}:3306
        env_file:
            - ./mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - essegroup
