version: '3.9'

x-php-cli: &php-cli
    build:
        context: ./php_cli
        dockerfile: Dockerfile
    # restart: unless-stopped
    working_dir: /var/project
    volumes:
        - ../:/var/project

services:
    # Nginx Service
    nginx:
        build:
            context:  ./nginx
            dockerfile: Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ../:/var/project
        ports:
            - ${NGINX_PORT}:80
        networks:
            - essegroup

    # PHP Service
    php-fpm:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
        restart: unless-stopped
        tty: true
        volumes:
            - ../:/var/project
        networks:
            - essegroup

    # PHP CLI Service
    php-cli:
        <<: *php-cli
        container_name: ${COMPOSE_PROJECT_NAME}-php-cli
        restart: 'no'
        networks:
            - essegroup

    # Mailhog Service
    mailhog:
        image: mailhog/mailhog:latest
        container_name: ${COMPOSE_PROJECT_NAME}-mailhog
        restart: unless-stopped
        depends_on:
            - php-fpm
        ports:
            - ${MAILHOG_INTERFACE_PORT}:8025
        networks:
            - essegroup

networks:
    essegroup:
        driver: bridge
