version: '3.9'

services:
    # Database Service
    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME?Not project name}-mysql
        ports:
            - ${MYSQL_SERVICE_PORT?Not mysql port}:3306
        env_file:
            - ./mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        #        entrypoint:
        #            sh -c "
        #                echo 'CREATE DATABASE IF NOT EXISTS admindatabase; GRANT ALL PRIVILEGES ON firstSchema.* TO '\''esseelitegroup'\''@'\''%'\''; ' > /docker-entrypoint-initdb.d/init.sql;
        #                echo 'CREATE DATABASE IF NOT EXISTS companydatabase; GRANT ALL PRIVILEGES ON secondSchema.* TO '\''esseelitegroup'\''@'\''%'\''; ' >> /docker-entrypoint-initdb.d/init.sql;
        #                /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        #            "
        networks:
            - essegroup
networks:
    essegroup:
        external: true