<?php

declare(strict_types=1);

namespace Project\Domains\Admin\Authentication\Infrastructure\Repositories\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240323112021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE university_application_additional_documents (uuid VARCHAR(255) NOT NULL, application_uuid VARCHAR(255) DEFAULT NULL, description VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_EA2F9D972693382E (application_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_biometric_photos (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_equivalence_documents (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_passport_translations (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_passports (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_school_attestat_translations (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_school_attestats (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_status_note_translations (id INT AUTO_INCREMENT NOT NULL, status_uuid INT DEFAULT NULL, locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX IDX_1D35AD50E979FD32 (status_uuid), UNIQUE INDEX university_application_status_note_translation_idx (locale, field, status_uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_statuses (id INT AUTO_INCREMENT NOT NULL, application_uuid VARCHAR(255) NOT NULL, value VARCHAR(20) NOT NULL, note LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_9916C3B02693382E (application_uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_transcript_translations (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_application_transcripts (uuid VARCHAR(255) NOT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) NOT NULL, extension VARCHAR(255) NOT NULL, size INT NOT NULL, path VARCHAR(255) NOT NULL, full_path VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, file_original_name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, url_pattern VARCHAR(255) NOT NULL, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_applications (uuid VARCHAR(255) NOT NULL, company_uuid VARCHAR(255) NOT NULL, university_uuid VARCHAR(255) NOT NULL, country_uuid VARCHAR(255) NOT NULL, passport_uuid VARCHAR(255) NOT NULL, school_attestat_uuid VARCHAR(255) NOT NULL, equivalence_document_uuid VARCHAR(255) NOT NULL, passport_translation_uuid VARCHAR(255) NOT NULL, transcript_uuid VARCHAR(255) NOT NULL, transcript_translation_uuid VARCHAR(255) NOT NULL, school_attestat_translation_uuid VARCHAR(255) NOT NULL, biometric_photo_uuid VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, birthday DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', father_name VARCHAR(255) DEFAULT NULL, mother_name VARCHAR(255) DEFAULT NULL, passport_number VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, friend_phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, home_address VARCHAR(255) DEFAULT NULL, creator_role VARCHAR(255) NOT NULL, is_agreed_to_share_data TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D4005ABD92124A48 (company_uuid), INDEX IDX_D4005ABD4C981D05 (university_uuid), INDEX IDX_D4005ABD249D38BF (passport_uuid), INDEX IDX_D4005ABDB84402F5 (school_attestat_uuid), INDEX IDX_D4005ABDAC402B00 (equivalence_document_uuid), INDEX IDX_D4005ABD688D08B4 (passport_translation_uuid), INDEX IDX_D4005ABD38B6E413 (transcript_uuid), INDEX IDX_D4005ABDED7DC213 (transcript_translation_uuid), INDEX IDX_D4005ABDF7B95114 (school_attestat_translation_uuid), INDEX IDX_D4005ABD652ED7E7 (biometric_photo_uuid), INDEX IDX_D4005ABD564CDB42 (country_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_applications_departments (application_uuid VARCHAR(255) NOT NULL, department_uuid VARCHAR(255) NOT NULL, INDEX IDX_71A8C7B52693382E (application_uuid), INDEX IDX_71A8C7B5736537F3 (department_uuid), PRIMARY KEY(application_uuid, department_uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_companies (uuid VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, domain VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_B4FFFDEE5E237E06 (name), UNIQUE INDEX UNIQ_B4FFFDEEA7A91E0B (domain), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_department_translations (id INT AUTO_INCREMENT NOT NULL, department_uuid VARCHAR(255) DEFAULT NULL, locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX IDX_31445EBD736537F3 (department_uuid), UNIQUE INDEX university_department_translation_idx (locale, field, department_uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_departments (uuid VARCHAR(255) NOT NULL, university_uuid VARCHAR(255) NOT NULL, company_uuid VARCHAR(255) NOT NULL, faculty_uuid VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, description text DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_6F54A234C981D05 (university_uuid), INDEX IDX_6F54A2392124A48 (company_uuid), INDEX IDX_6F54A235432B5F3 (faculty_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_universities (uuid VARCHAR(255) NOT NULL, company_uuid VARCHAR(255) NOT NULL, logo_uuid VARCHAR(255) DEFAULT NULL, cover_uuid VARCHAR(255) DEFAULT NULL, country_uuid VARCHAR(255) DEFAULT NULL, city_uuid VARCHAR(255) DEFAULT NULL, youtube_video_id VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, description text DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_C0A95993A85ECC4D (logo_uuid), UNIQUE INDEX UNIQ_C0A95993E5A3194F (cover_uuid), INDEX IDX_C0A9599392124A48 (company_uuid), INDEX IDX_C0A95993564CDB42 (country_uuid), INDEX IDX_C0A9599332316DCE (city_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE university_university_translations (id INT AUTO_INCREMENT NOT NULL, university_uuid VARCHAR(255) DEFAULT NULL, locale VARCHAR(8) NOT NULL, field VARCHAR(32) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX IDX_E9F000324C981D05 (university_uuid), UNIQUE INDEX university_university_translation_idx (locale, university_uuid, field), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE university_application_additional_documents ADD CONSTRAINT FK_EA2F9D972693382E FOREIGN KEY (application_uuid) REFERENCES university_applications (uuid)');
        $this->addSql('ALTER TABLE university_application_status_note_translations ADD CONSTRAINT FK_1D35AD50E979FD32 FOREIGN KEY (status_uuid) REFERENCES university_application_statuses (id)');
        $this->addSql('ALTER TABLE university_application_statuses ADD CONSTRAINT FK_9916C3B02693382E FOREIGN KEY (application_uuid) REFERENCES university_applications (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABD92124A48 FOREIGN KEY (company_uuid) REFERENCES university_companies (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABD4C981D05 FOREIGN KEY (university_uuid) REFERENCES university_universities (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABD249D38BF FOREIGN KEY (passport_uuid) REFERENCES university_application_passports (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABDB84402F5 FOREIGN KEY (school_attestat_uuid) REFERENCES university_application_school_attestats (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABDAC402B00 FOREIGN KEY (equivalence_document_uuid) REFERENCES university_application_equivalence_documents (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABD688D08B4 FOREIGN KEY (passport_translation_uuid) REFERENCES university_application_passport_translations (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABD38B6E413 FOREIGN KEY (transcript_uuid) REFERENCES university_application_transcripts (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABDED7DC213 FOREIGN KEY (transcript_translation_uuid) REFERENCES university_application_transcript_translations (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABDF7B95114 FOREIGN KEY (school_attestat_translation_uuid) REFERENCES university_application_school_attestat_translations (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABD652ED7E7 FOREIGN KEY (biometric_photo_uuid) REFERENCES university_application_biometric_photos (uuid)');
        $this->addSql('ALTER TABLE university_applications ADD CONSTRAINT FK_D4005ABD564CDB42 FOREIGN KEY (country_uuid) REFERENCES country_countries (uuid)');
        $this->addSql('ALTER TABLE university_applications_departments ADD CONSTRAINT FK_71A8C7B52693382E FOREIGN KEY (application_uuid) REFERENCES university_applications (uuid)');
        $this->addSql('ALTER TABLE university_applications_departments ADD CONSTRAINT FK_71A8C7B5736537F3 FOREIGN KEY (department_uuid) REFERENCES university_departments (uuid)');
        $this->addSql('ALTER TABLE university_department_translations ADD CONSTRAINT FK_31445EBD736537F3 FOREIGN KEY (department_uuid) REFERENCES university_departments (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE university_departments ADD CONSTRAINT FK_6F54A234C981D05 FOREIGN KEY (university_uuid) REFERENCES university_universities (uuid)');
        $this->addSql('ALTER TABLE university_departments ADD CONSTRAINT FK_6F54A2392124A48 FOREIGN KEY (company_uuid) REFERENCES university_companies (uuid)');
        $this->addSql('ALTER TABLE university_departments ADD CONSTRAINT FK_6F54A235432B5F3 FOREIGN KEY (faculty_uuid) REFERENCES faculty_faculties (uuid)');
        $this->addSql('ALTER TABLE university_universities ADD CONSTRAINT FK_C0A95993A85ECC4D FOREIGN KEY (logo_uuid) REFERENCES university_logos (uuid)');
        $this->addSql('ALTER TABLE university_universities ADD CONSTRAINT FK_C0A95993E5A3194F FOREIGN KEY (cover_uuid) REFERENCES university_covers (uuid)');
        $this->addSql('ALTER TABLE university_universities ADD CONSTRAINT FK_C0A9599392124A48 FOREIGN KEY (company_uuid) REFERENCES university_companies (uuid)');
        $this->addSql('ALTER TABLE university_universities ADD CONSTRAINT FK_C0A95993564CDB42 FOREIGN KEY (country_uuid) REFERENCES country_countries (uuid)');
        $this->addSql('ALTER TABLE university_universities ADD CONSTRAINT FK_C0A9599332316DCE FOREIGN KEY (city_uuid) REFERENCES country_cities (uuid)');
        $this->addSql('ALTER TABLE university_university_translations ADD CONSTRAINT FK_E9F000324C981D05 FOREIGN KEY (university_uuid) REFERENCES university_universities (uuid) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_additional_documents DROP FOREIGN KEY FK_2D5581272693382E');
        $this->addSql('ALTER TABLE application_status_note_translations DROP FOREIGN KEY FK_C5AB7FB1E979FD32');
        $this->addSql('ALTER TABLE application_statuses DROP FOREIGN KEY FK_F4CBC1022693382E');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0564CDB42');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0249D38BF');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F038B6E413');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F04C981D05');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0652ED7E7');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0688D08B4');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F092124A48');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0AC402B00');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0B84402F5');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0ED7DC213');
        $this->addSql('ALTER TABLE applications DROP FOREIGN KEY FK_F7C966F0F7B95114');
        $this->addSql('ALTER TABLE applications_departments DROP FOREIGN KEY FK_C2C2337D2693382E');
        $this->addSql('ALTER TABLE applications_departments DROP FOREIGN KEY FK_C2C2337D736537F3');
        $this->addSql('ALTER TABLE department_translations DROP FOREIGN KEY FK_3DCAB845736537F3');
        $this->addSql('ALTER TABLE departments DROP FOREIGN KEY FK_16AEB8D45432B5F3');
        $this->addSql('ALTER TABLE departments DROP FOREIGN KEY FK_16AEB8D492124A48');
        $this->addSql('ALTER TABLE departments DROP FOREIGN KEY FK_16AEB8D44C981D05');
        $this->addSql('ALTER TABLE universities DROP FOREIGN KEY FK_E36065DE92124A48');
        $this->addSql('ALTER TABLE universities DROP FOREIGN KEY FK_E36065DEA85ECC4D');
        $this->addSql('ALTER TABLE universities DROP FOREIGN KEY FK_E36065DEE5A3194F');
        $this->addSql('ALTER TABLE universities DROP FOREIGN KEY FK_E36065DE564CDB42');
        $this->addSql('ALTER TABLE universities DROP FOREIGN KEY FK_E36065DE32316DCE');
        $this->addSql('ALTER TABLE university_translations DROP FOREIGN KEY FK_E57EE6CA4C981D05');
        $this->addSql('DROP TABLE application_additional_documents');
        $this->addSql('DROP TABLE application_biometric_photos');
        $this->addSql('DROP TABLE application_equivalence_documents');
        $this->addSql('DROP TABLE application_passport_translations');
        $this->addSql('DROP TABLE application_passports');
        $this->addSql('DROP TABLE application_school_attestat_translations');
        $this->addSql('DROP TABLE application_school_attestats');
        $this->addSql('DROP TABLE application_status_note_translations');
        $this->addSql('DROP TABLE application_statuses');
        $this->addSql('DROP TABLE application_transcript_translations');
        $this->addSql('DROP TABLE application_transcripts');
        $this->addSql('DROP TABLE applications');
        $this->addSql('DROP TABLE applications_departments');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE department_translations');
        $this->addSql('DROP TABLE departments');
        $this->addSql('DROP TABLE universities');
        $this->addSql('DROP TABLE university_translations');
        $this->addSql('ALTER TABLE faculty_faculties CHANGE description description text DEFAULT NULL');
        $this->addSql('ALTER TABLE faculty_faculties ADD CONSTRAINT FK_357BE7CF92124A48 FOREIGN KEY (company_uuid) REFERENCES university_companies (uuid)');
        $this->addSql('ALTER TABLE faculty_faculties ADD CONSTRAINT FK_357BE7CF4C981D05 FOREIGN KEY (university_uuid) REFERENCES university_universities (uuid)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE faculty_faculties DROP FOREIGN KEY FK_357BE7CF92124A48');
        $this->addSql('ALTER TABLE faculty_faculties DROP FOREIGN KEY FK_357BE7CF4C981D05');
        $this->addSql('CREATE TABLE application_additional_documents (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, application_uuid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, description VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_2D5581272693382E (application_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_biometric_photos (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_equivalence_documents (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_passport_translations (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_passports (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_school_attestat_translations (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_school_attestats (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_status_note_translations (id INT AUTO_INCREMENT NOT NULL, status_uuid INT DEFAULT NULL, locale VARCHAR(8) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, field VARCHAR(32) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, content LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IDX_C5AB7FB1E979FD32 (status_uuid), UNIQUE INDEX university_application_status_note_translation_idx (locale, field, status_uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_statuses (id INT AUTO_INCREMENT NOT NULL, application_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, value VARCHAR(20) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, note LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F4CBC1022693382E (application_uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_transcript_translations (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE application_transcripts (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, width INT DEFAULT NULL, height INT DEFAULT NULL, mime_type VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, extension VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, size INT NOT NULL, path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_path VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, file_original_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, url_pattern VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, downloaded_count INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE applications (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, company_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, university_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, country_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, passport_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, school_attestat_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, equivalence_document_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, passport_translation_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, transcript_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, transcript_translation_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, school_attestat_translation_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, biometric_photo_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, full_name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, birthday DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', father_name VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, mother_name VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, passport_number VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, phone VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, friend_phone VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, home_address VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, creator_role VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, is_agreed_to_share_data TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F7C966F092124A48 (company_uuid), INDEX IDX_F7C966F0564CDB42 (country_uuid), INDEX IDX_F7C966F0652ED7E7 (biometric_photo_uuid), INDEX IDX_F7C966F0F7B95114 (school_attestat_translation_uuid), INDEX IDX_F7C966F0ED7DC213 (transcript_translation_uuid), INDEX IDX_F7C966F038B6E413 (transcript_uuid), INDEX IDX_F7C966F0688D08B4 (passport_translation_uuid), INDEX IDX_F7C966F0AC402B00 (equivalence_document_uuid), INDEX IDX_F7C966F0B84402F5 (school_attestat_uuid), INDEX IDX_F7C966F0249D38BF (passport_uuid), INDEX IDX_F7C966F04C981D05 (university_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE applications_departments (application_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, department_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IDX_C2C2337D736537F3 (department_uuid), INDEX IDX_C2C2337D2693382E (application_uuid), PRIMARY KEY(application_uuid, department_uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE companies (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, domain VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, status VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8244AA3AA7A91E0B (domain), UNIQUE INDEX UNIQ_8244AA3A5E237E06 (name), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE department_translations (id INT AUTO_INCREMENT NOT NULL, department_uuid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, locale VARCHAR(8) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, field VARCHAR(32) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, content LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IDX_3DCAB845736537F3 (department_uuid), UNIQUE INDEX department_translation_idx (locale, field, department_uuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE departments (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, university_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, company_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, faculty_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, name VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, description TEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_16AEB8D45432B5F3 (faculty_uuid), INDEX IDX_16AEB8D492124A48 (company_uuid), INDEX IDX_16AEB8D44C981D05 (university_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE universities (uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, company_uuid VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, logo_uuid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, cover_uuid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, country_uuid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, city_uuid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, youtube_video_id VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, name VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, label VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, description TEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_E36065DE32316DCE (city_uuid), INDEX IDX_E36065DE564CDB42 (country_uuid), INDEX IDX_E36065DE92124A48 (company_uuid), UNIQUE INDEX UNIQ_E36065DEE5A3194F (cover_uuid), UNIQUE INDEX UNIQ_E36065DEA85ECC4D (logo_uuid), PRIMARY KEY(uuid)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE university_translations (id INT AUTO_INCREMENT NOT NULL, university_uuid VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, locale VARCHAR(8) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, field VARCHAR(32) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, content LONGTEXT CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IDX_E57EE6CA4C981D05 (university_uuid), UNIQUE INDEX university_translation_idx (locale, university_uuid, field), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE application_additional_documents ADD CONSTRAINT FK_2D5581272693382E FOREIGN KEY (application_uuid) REFERENCES applications (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE application_status_note_translations ADD CONSTRAINT FK_C5AB7FB1E979FD32 FOREIGN KEY (status_uuid) REFERENCES application_statuses (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE application_statuses ADD CONSTRAINT FK_F4CBC1022693382E FOREIGN KEY (application_uuid) REFERENCES applications (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0564CDB42 FOREIGN KEY (country_uuid) REFERENCES country_countries (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0249D38BF FOREIGN KEY (passport_uuid) REFERENCES application_passports (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F038B6E413 FOREIGN KEY (transcript_uuid) REFERENCES application_transcripts (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F04C981D05 FOREIGN KEY (university_uuid) REFERENCES universities (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0652ED7E7 FOREIGN KEY (biometric_photo_uuid) REFERENCES application_biometric_photos (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0688D08B4 FOREIGN KEY (passport_translation_uuid) REFERENCES application_passport_translations (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F092124A48 FOREIGN KEY (company_uuid) REFERENCES companies (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0AC402B00 FOREIGN KEY (equivalence_document_uuid) REFERENCES application_equivalence_documents (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0B84402F5 FOREIGN KEY (school_attestat_uuid) REFERENCES application_school_attestats (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0ED7DC213 FOREIGN KEY (transcript_translation_uuid) REFERENCES application_transcript_translations (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications ADD CONSTRAINT FK_F7C966F0F7B95114 FOREIGN KEY (school_attestat_translation_uuid) REFERENCES application_school_attestat_translations (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications_departments ADD CONSTRAINT FK_C2C2337D2693382E FOREIGN KEY (application_uuid) REFERENCES applications (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE applications_departments ADD CONSTRAINT FK_C2C2337D736537F3 FOREIGN KEY (department_uuid) REFERENCES departments (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE department_translations ADD CONSTRAINT FK_3DCAB845736537F3 FOREIGN KEY (department_uuid) REFERENCES departments (uuid) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE departments ADD CONSTRAINT FK_16AEB8D45432B5F3 FOREIGN KEY (faculty_uuid) REFERENCES faculty_faculties (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE departments ADD CONSTRAINT FK_16AEB8D492124A48 FOREIGN KEY (company_uuid) REFERENCES companies (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE departments ADD CONSTRAINT FK_16AEB8D44C981D05 FOREIGN KEY (university_uuid) REFERENCES universities (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE universities ADD CONSTRAINT FK_E36065DE92124A48 FOREIGN KEY (company_uuid) REFERENCES companies (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE universities ADD CONSTRAINT FK_E36065DEA85ECC4D FOREIGN KEY (logo_uuid) REFERENCES university_logos (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE universities ADD CONSTRAINT FK_E36065DEE5A3194F FOREIGN KEY (cover_uuid) REFERENCES university_covers (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE universities ADD CONSTRAINT FK_E36065DE564CDB42 FOREIGN KEY (country_uuid) REFERENCES country_countries (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE universities ADD CONSTRAINT FK_E36065DE32316DCE FOREIGN KEY (city_uuid) REFERENCES country_cities (uuid) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE university_translations ADD CONSTRAINT FK_E57EE6CA4C981D05 FOREIGN KEY (university_uuid) REFERENCES universities (uuid) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE university_application_additional_documents DROP FOREIGN KEY FK_EA2F9D972693382E');
        $this->addSql('ALTER TABLE university_application_status_note_translations DROP FOREIGN KEY FK_1D35AD50E979FD32');
        $this->addSql('ALTER TABLE university_application_statuses DROP FOREIGN KEY FK_9916C3B02693382E');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABD92124A48');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABD4C981D05');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABD249D38BF');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABDB84402F5');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABDAC402B00');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABD688D08B4');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABD38B6E413');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABDED7DC213');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABDF7B95114');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABD652ED7E7');
        $this->addSql('ALTER TABLE university_applications DROP FOREIGN KEY FK_D4005ABD564CDB42');
        $this->addSql('ALTER TABLE university_applications_departments DROP FOREIGN KEY FK_71A8C7B52693382E');
        $this->addSql('ALTER TABLE university_applications_departments DROP FOREIGN KEY FK_71A8C7B5736537F3');
        $this->addSql('ALTER TABLE university_department_translations DROP FOREIGN KEY FK_31445EBD736537F3');
        $this->addSql('ALTER TABLE university_departments DROP FOREIGN KEY FK_6F54A234C981D05');
        $this->addSql('ALTER TABLE university_departments DROP FOREIGN KEY FK_6F54A2392124A48');
        $this->addSql('ALTER TABLE university_departments DROP FOREIGN KEY FK_6F54A235432B5F3');
        $this->addSql('ALTER TABLE university_universities DROP FOREIGN KEY FK_C0A95993A85ECC4D');
        $this->addSql('ALTER TABLE university_universities DROP FOREIGN KEY FK_C0A95993E5A3194F');
        $this->addSql('ALTER TABLE university_universities DROP FOREIGN KEY FK_C0A9599392124A48');
        $this->addSql('ALTER TABLE university_universities DROP FOREIGN KEY FK_C0A95993564CDB42');
        $this->addSql('ALTER TABLE university_universities DROP FOREIGN KEY FK_C0A9599332316DCE');
        $this->addSql('ALTER TABLE university_university_translations DROP FOREIGN KEY FK_E9F000324C981D05');
        $this->addSql('DROP TABLE university_application_additional_documents');
        $this->addSql('DROP TABLE university_application_biometric_photos');
        $this->addSql('DROP TABLE university_application_equivalence_documents');
        $this->addSql('DROP TABLE university_application_passport_translations');
        $this->addSql('DROP TABLE university_application_passports');
        $this->addSql('DROP TABLE university_application_school_attestat_translations');
        $this->addSql('DROP TABLE university_application_school_attestats');
        $this->addSql('DROP TABLE university_application_status_note_translations');
        $this->addSql('DROP TABLE university_application_statuses');
        $this->addSql('DROP TABLE university_application_transcript_translations');
        $this->addSql('DROP TABLE university_application_transcripts');
        $this->addSql('DROP TABLE university_applications');
        $this->addSql('DROP TABLE university_applications_departments');
        $this->addSql('DROP TABLE university_companies');
        $this->addSql('DROP TABLE university_department_translations');
        $this->addSql('DROP TABLE university_departments');
        $this->addSql('DROP TABLE university_universities');
        $this->addSql('DROP TABLE university_university_translations');
        $this->addSql('ALTER TABLE faculty_faculties CHANGE description description TEXT DEFAULT NULL');
    }
}
