<?php

namespace App\Exceptions;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpFoundation\JsonResponse;
use Illuminate\Http\Response;
use Illuminate\Validation\ValidationException;
use Project\Shared\Domain\DomainException;
use Symfony\Component\HttpFoundation\Exception\BadRequestException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Messenger\Exception\HandlerFailedException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    /**
     * @param $request
     * @param  Throwable  $ex
     * @return JsonResponse|\Illuminate\Http\Response|\Symfony\Component\HttpFoundation\Response
     *
     * @throws Throwable
     */
    public function render($request, Throwable $ex): JsonResponse
    {
        if ($ex instanceof DomainException) {
            return response()->json([
                'message' => $ex->getMessage(),
            ], $ex->getHttpResponseCode());
        }

        if ($ex instanceof ValidationException) {
            return response()->json([
                'message' => 'Validation exception',
                'errors' => $ex->errors(),
            ], Response::HTTP_UNPROCESSABLE_ENTITY);
        }

        if ($ex instanceof BadRequestException) {
            return response()->json([
                'message' => $ex->getMessage(),
                'error' => 'Bad request exception',
            ], Response::HTTP_BAD_REQUEST);
        }

        if ($ex instanceof NotFoundHttpException) {
            return response()->json(
                [
                    'message' => 'Not found http exception',
                    'error' => $ex->getMessage(),
                ],
                Response::HTTP_NOT_FOUND
            );
        }

        if ($ex instanceof AuthenticationException) {
            return response()->json(
                [
                    'message' => 'Authentication exception',
                    'error' => str_replace(['.'], [''], $ex->getMessage()), // 'Unauthorized',
                ],
                Response::HTTP_UNAUTHORIZED
            );
        }

        if ($ex instanceof HandlerFailedException) {
            $domainException = $ex->getPrevious();
            if ($domainException instanceof \Project\Shared\Domain\DomainException) {
                return response()->json(
                    [
                        'message' => $domainException->getMessage(),
                    ],
                    $domainException->getHttpResponseCode()
                );
                // return $domainException->response();
            }
        }

        return response()->json([
            // 'message' => 'Unauthenticated',
            'error' => $ex->getMessage(),
            'file' => $ex->getFile(),
            'line' => $ex->getLine(),
            'previous' => $ex->getPrevious(),
            'class' => $ex::class,
        ], Response::HTTP_INTERNAL_SERVER_ERROR);

        return parent::render($request, $ex); // TODO: Change the autogenerated stub
    }

    protected function unauthenticated($request, AuthenticationException $exception)
    {
        dd(__METHOD__);

        if ($request->expectsJson()) {
            return response()->json(['message' => 'Unauthenticated.'], 401);
        }

        if ($request->is('admin') || $request->is('admin/*')) {
            return redirect()->guest('/admin');
        }

        return redirect()->guest(route('login'));
    }
}
